const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
const COMMON_MODAL_DATA_SET = 'COMMON_MODAL_DATA_SET';
const LOADER_SHOW = 'LOADER_SHOW';
const LOADER_HIDE = 'LOADER_HIDE';
const UPDATE_IS_AUTHENTICATEED = 'UPDATE_IS_AUTHENTICATEED';
const SET_GLOBAL_SETTINGS = 'SET_GLOBAL_SETTINGS';
const TEST_DATA_UPDATE = 'TEST_DATA_UPDATE';
const SET_VALIDITY = 'SET_VALIDITY';
export {
  IS_AUTHENTICATED,
  COMMON_MODAL_DATA_SET,
  LOADER_SHOW,
  LOADER_HIDE,
  UPDATE_IS_AUTHENTICATEED,
  TEST_DATA_UPDATE,
  SET_GLOBAL_SETTINGS,SET_VALIDITY
};
